# Generated by Django 2.1.7 on 2019-04-18 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=60)),
                ('description', models.CharField(blank=None, max_length=255)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='app-id')),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_by_user', to='applications.Application')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_by_user', to='auth.UserProfile')),
            ],
            options={
                'verbose_name': 'Users by App',
                'verbose_name_plural': 'Users by App',
            },
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_bg_img', models.ImageField(blank=True, null=True, upload_to='login_bg_img/', verbose_name='Login screen Image')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', related_query_name='config', to='applications.Application')),
            ],
            options={
                'verbose_name': 'Application Configuration',
            },
        ),
        migrations.CreateModel(
            name='ApplicationUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=None, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='applications.Application')),
            ],
        ),
    ]
