# Generated by Django 2.1.7 on 2019-04-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbyuser',
            name='user_role',
            field=models.ForeignKey(default='CST', on_delete=django.db.models.deletion.PROTECT, to='useraccounts.UserRole'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationbyuser',
            unique_together={('application', 'user_role')},
        ),
    ]
